unpacked 08042014 2_00_00_00 msp430-gcc-14r1-10-source.tar.bz2
18827a77f0c572890159d95aa5c79d23  # md5
93ebed10bf4cb9bd0dcae247d1b5f2c9d05c88a8fca5d86a6bb01aa1dcb45534  # sha256
http://software-dl.ti.com/msp430/msp430_public_sw/mcu/msp430/MSPGCC/latest/exports/msp430-gcc-14r1-10-source.tar.bz2

diff --git a/tools/dejagnu/runtest b/tools/dejagnu/runtest
--- a/tools/dejagnu/runtest
+++ b/tools/dejagnu/runtest
@@ -1,14 +1,29 @@
 #!/bin/sh
 #
-# runtest -- basically all this script does is find the proper expect
-#	     shell and then run DejaGnu.
+# Copyright (C) 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000,
+# 2001, 2002, 2003, 2004 Free Software Foundation, Inc.
 #
-# Written by Rob Savoye <rob@welcomehome.org>
+# This file is part of DejaGnu.
 #
+# DejaGnu is free software; you can redistribute it and/or modify it
+# under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 2 of the License, or
+# (at your option) any later version.
+#
+# DejaGnu is distributed in the hope that it will be useful, but
+# WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
+# General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with DejaGnu; if not, write to the Free Software Foundation,
+# Inc., 51 Franklin Street - Fifth Floor, Boston, MA 02110-1301, USA.
 
-#
+# This script was written by Rob Savoye. The script finds the proper
+# expect shell and then starts DejaGnu.
+
 # Get the execution path to this script and the current directory.
-#
+
 mypath=${0-.}
 if expr ${mypath} : '.*/.*' > /dev/null
 then
@@ -27,11 +42,10 @@ else
     IFS="$save_ifs"
 fi
 execpath=`echo ${mypath} | sed  -e 's@/[^/]*$@@'`
-# rootme=`pwd`
 
-#
-# get the name by which runtest was invoked and extract the config triplet
-#
+# Get the name by which runtest was invoked and extract the config
+# triplet.
+
 runtest=`echo ${mypath} | sed -e 's@^.*/@@'`
 target=`echo $runtest | sed -e 's/-runtest$//'`
 if [ "$target" != runtest ] ; then
@@ -40,11 +54,10 @@ else
     target=""
 fi
 
-#
-# Find the right expect binary to use. If a variable EXPECT exists,
-# it takes precedence over all other tests. Otherwise look for a freshly
+# Find the right expect binary to use. If a variable EXPECT exists, it
+# takes precedence over all other tests. Otherwise look for a freshly
 # built one, and then use one in the path.
-#
+
 if [ x"$EXPECT" != x ] ; then
   expectbin=$EXPECT
 else
@@ -55,20 +68,21 @@ else
     fi
 fi
 
-# just to be safe...
+# Just to be safe ..
+
 if [ -z "$expectbin" ]; then
   echo "ERROR: No expect shell found"
   exit 1
 fi
 
-# This wrapper script will set up run-time library search PATHs
+# This wrapper script will set up run-time library search PATHs.
+
 if [ -x "$expectbin-bld.sh" ]; then
   expectbin="${CONFIG_SHELL-/bin/sh} $expectbin-bld.sh"
 fi
 
-#
 # Extract a few options from the option list.
-#
+
 verbose=0
 debug=""
 for a in "$@" ; do
@@ -83,19 +97,18 @@ if expr $verbose \> 0 > /dev/null ; then
   echo Expect binary is $expectbin
 fi
 
+# Find runtest.exp. First we look in its installed location,
+# otherwise start if from the source tree.
 #
-# find runtest.exp. First we look in it's installed location, otherwise
-# start if from the source tree.
+# runtest.exp is found in @datadir@ (set by configure), but $execpath
+# is @bindir@.  We're assuming that:
 #
-# runtest.exp is found in (autoconf-configure-set) @datadir@, but
-# $execpath is @bindir@.  We're assuming that
+#   @datadir@ == @bindir@/../share
+#   or
+#   @datadir@ == @bindir@/../../share
 #
-# @datadir@ == @bindir@/../share
-# or
-# @datadir@ == @bindir@/../../share
-#
-# which is a very weak assumption
-#
+# .. which is a very weak assumption
+
 for i in `echo ${execpath} | sed  -e 's@/[^/]*$@/share/dejagnu@'` `echo ${execpath} | sed  -e 's@/[^/]*/[^/]*$@/share/dejagnu@'` $execpath ; do
     if expr $verbose \> 1 > /dev/null ; then
 	echo Looking for $i/runtest.exp.
@@ -108,7 +121,9 @@ for i in `echo ${execpath} | sed  -e 's@/[^/]*$@/share/dejagnu@'` `echo ${execpa
         break;
     fi
 done
-# check for an environment variable
+
+# Check for an environment variable.
+
 if [ x"$DEJAGNULIBS" != x ] ; then
     runpath=$DEJAGNULIBS
     if expr $verbose \> 0 > /dev/null ; then
@@ -116,7 +131,12 @@ if [ x"$DEJAGNULIBS" != x ] ; then
     fi
 fi
 if [ x"$runpath" = x ] ; then
-    echo "ERROR: runtest.exp does not exist."
+    echo "ERROR: runtest.exp does not exist"
+    exit 1
+fi
+
+if ! type $expectbin >/dev/null 2>/dev/null ; then
+    echo "ERROR: unable to find expect on the PATH"
     exit 1
 fi
 
